<?php

namespace core\config;

class FConstants {
	const ACTION_CONFIG = "ACTION_CONFIG";
	const FILTER_CONFIG = "FILTER_CONFIG";
	const LAYOUT_CONFIG = "LAYOUT_CONFIG";
	const REDIRECT_CONFIG = "REDIRECT_CONFIG";
	const FRIENDLY_URL_CONFIG = "FRIENDLY_URL_CONFIG";
	const MODULE_SPECIFIC_CONFIG = "MODULE_SPECIFIC_CONFIG";
	const PERMISSION_CONFIG = "PERMISSION_CONFIG";
	const MODULE_CONFIG = "MODULE_CONFIG";
	const APP_SETTINGS = "APP_SETTINGS";
	const WORKFLOW_CONFIG = "WORKFLOW_CONFIG";
	const VIEW_PATH = "VIEW_PATH";
	const LAYOUT_PATH = "LAYOUT_PATH";
	const MODULE_PATH = "MODULE_PATH";
	const CONFIG_PATH = "CONFIG_PATH";
	const COMMON_CONFIG = "COMMON_CONFIG";
	const SPECIFIC_CONFIG = "SPECIFIC_CONFIG";
	const RELATIVE_RESOURCE_PATH = "RELATIVE_RESOURCE_PATH";
	const SUSCESS = "SUCCESS";
	const ERROR = "ERROR";
	const YES_FLAG = "Y";
	const NO_FLAG = "N";
}