<?php

namespace common\config;

use core\config\FAttributes;

class Attributes extends FAttributes {
	const CURRENCE_CODE = "CURRENCE_CODE";
	const PRODUCT_ID = "PRODUCT_ID";
	const PRODUCT_QUANTITY = "PRODUCT_QUANTITY";
	const CUSTOMER_ID = "CUSTOMER_ID";
	const ATTR_ERROR_MESSAGE = "ERROR_MESSAGE";
	const PRODUCT_BASE_PRICE = "PRODUCT_BASE_PRICE";
	const BULK_DISCOUNT_INFO = "BULK_DISCOUNT_INFO";
	const PRICE_LEVEL_INFO = "PRICE_LEVEL_INFO";
	const DISCOUNT_AMOUNT = "DISCOUNT_AMOUNT";
	const DISCOUNT_PERCENT = "DISCOUNT_PERCENT";
	const DISCOUNT_COUPON_AMOUNT = "DISCOUNT_COUPON_AMOUNT";
	const PRODUCT_TAX_LIST = "PRODUCT_TAX_LIST";
	const SHIPPING_TAX_LIST = "SHIPPING_TAX_LIST";
	const SHIPPING_ADDRESS = "SHIPPING_ADDRESS";
	const BILLING_ADDRESS = "BILLING_ADDRESS";
	const TAX_AMOUNT = "TAX_AMOUNT";
	const SALE_PRICE = "SALE_PRICE";
	const DISCOUNT_COUPON_CODE = "DISCOUNT_COUPON_CODE";
	const DISCOUNT_COUPON_INFO = "DISCOUNT_COUPON_INFO";
	const DISCOUNT_COUPON_APPLICABLE_ITEMS = "DISCOUNT_COUPON_APPLICABLE_ITEMS";
	const SHOPPING_CART = "SHOPPING_CART";
	const BACKUP_SHOPPING_CART = "BACKUP_SHOPPING_CART";
	const PRODUCT_TAX_PERCENT = "PRODUCT_TAX_PERCENT";
	const SHIPPING_TAX_PERCENT = "SHIPPING_TAX_PERCENT";
	const SUB_TOTAL_AMOUNT = "SUB_TOTAL_AMOUNT";
	const SHIPPING_COST = "SHIPPING_COST";
	const ORDER_PRODUCT_LIST = "ORDER_PRODUCT_LIST";
	const SHIPPING_METHOD_ID = "SHIPPING_METHOD_ID";
	const SHIPPING_METHOD_INFO = "SHIPPING_METHOD_INFO";
	const ORDER_TOTALS = "ORDER_TOTALS";

	const FILTER_VO = "filter_vo";
	const ATTR_MESSAGE = "attr_message";

	const FILE_NAME = "file_name";
	const FILE_PATH = "file_path";
	const LIST_ORDER_IDS = "list_order_ids";

	const PENDING_ORDER_LIST = "pending_order_list";
}